export const ENV = {
  jwtSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  isProduction: process.env.NODE_ENV === "production",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  llmProvider: (process.env.LLM_PROVIDER || "gemini") as "openai" | "gemini" | "groq",
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME ?? "",
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY ?? "",
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET ?? "",
  forgeApiUrl: process.env.FORGE_API_URL ?? "",
  forgeApiKey: process.env.FORGE_API_KEY ?? "",
  bundleSocialApiKey: process.env.BUNDLE_SOCIAL_API_KEY ?? "",
  huggingFaceApiKey: process.env.HUGGINGFACE_API_KEY ?? "",
  falApiKey: process.env.FAL_API_KEY ?? "",
  minimaxApiKey: process.env.MINIMAX_API_KEY ?? "",
  magicHourApiKey: process.env.MAGIC_HOUR_API_KEY ?? "",
  wavespeedApiKey: process.env.WAVESPEED_API_KEY ?? "",
};
